import type { WorkspaceFilePreview } from "../workspace-contracts";
import { previewWorkspaceFile } from "./workspace-files";

const REFERENCE_PATTERN = /@\{([^}\r\n]+)\}(?:#L(\d+)(?:-L(\d+))?)?/g;
const MAX_REFERENCES = 3;
const MAX_REFERENCE_CONTEXT_BYTES = 200 * 1024;
const CONTEXT_START = "\n\n<<<pi-web:workspace-context:v1";
const CONTEXT_END = "\n<<<pi-web:end-workspace-context:v1>>>";

type WorkspaceReference = {
  raw: string;
  path: string;
  startLine?: number;
  endLine?: number;
};

type PreviewLoader = (relativePath: string) => Promise<WorkspaceFilePreview>;

function parsePositiveLine(value: string | undefined): number | undefined {
  if (!value) return undefined;
  const line = Number(value);
  return Number.isSafeInteger(line) && line > 0 ? line : undefined;
}

function parseReferences(prompt: string): WorkspaceReference[] {
  const references: WorkspaceReference[] = [];
  for (const match of prompt.matchAll(REFERENCE_PATTERN)) {
    if (references.length >= MAX_REFERENCES) break;
    const path = match[1]?.trim();
    const startLine = parsePositiveLine(match[2]);
    const endLine = parsePositiveLine(match[3]);
    if (!path || (match[3] && !endLine) || (startLine && endLine && endLine < startLine)) continue;
    references.push({ raw: match[0], path, startLine, endLine });
  }
  return references;
}

function contextStart(promptLength: number): string {
  return `${CONTEXT_START} user-chars=${promptLength}>>>\n`;
}

function truncatedReferenceNotice(preview: WorkspaceFilePreview, isWholeFileReference: boolean): string {
  if (!preview.truncated || !isWholeFileReference) return "";
  return `\n[Preview truncated: this file has ${preview.totalLines} lines; only lines 1-2000 are included. Use workspace_read with path \"${preview.path}\" and offset 2001 to read the remaining lines.]`;
}

/**
 * Adds bounded, validated file text for the explicit @{relative/path} tokens
 * generated by the UI. The internal suffix preserves a model-only context while
 * `visibleWorkspacePrompt()` restores the original user text for session UI.
 */
export async function expandWorkspaceReferences(prompt: string, loadPreview: PreviewLoader = previewWorkspaceFile): Promise<string> {
  const references = parseReferences(prompt);
  if (references.length === 0) return prompt;

  const sections: string[] = [];
  let bytes = 0;
  const seen = new Set<string>();

  for (const reference of references) {
    const identity = `${reference.path}:${reference.startLine ?? ""}:${reference.endLine ?? ""}`;
    if (seen.has(identity)) continue;
    seen.add(identity);

    try {
      const preview = await loadPreview(reference.path);
      const lines = preview.content.split("\n");
      const start = reference.startLine ?? 1;
      const end = reference.endLine ?? (reference.startLine ?? lines.length);
      if (start > lines.length || end > lines.length) continue;

      const selected = lines.slice(start - 1, end).join("\n");
      const label = reference.startLine
        ? `${preview.path}#L${start}${end !== start ? `-L${end}` : ""}`
        : preview.path;
      const section = `\n\n[Workspace reference: ${label}]\n${selected}${truncatedReferenceNotice(preview, reference.startLine === undefined)}\n[End workspace reference]`;
      const sectionBytes = Buffer.byteLength(section, "utf8");
      if (bytes + sectionBytes > MAX_REFERENCE_CONTEXT_BYTES) break;
      bytes += sectionBytes;
      sections.push(section);
    } catch {
      // Keep the original token in the visible prompt. The model can still use
      // workspace tools, while an invalid path is never read implicitly.
    }
  }

  return sections.length > 0 ? `${prompt}${contextStart(prompt.length)}${sections.join("")}${CONTEXT_END}` : prompt;
}

function visibleMarkedWorkspacePrompt(content: string): string | undefined {
  if (!content.endsWith(CONTEXT_END)) return undefined;
  const suffixStart = content.lastIndexOf(CONTEXT_START);
  if (suffixStart === -1) return undefined;

  const headerEnd = content.indexOf(">>>\n", suffixStart);
  if (headerEnd === -1) return undefined;
  const header = content.slice(suffixStart, headerEnd + 4);
  const match = /^\n\n<<<pi-web:workspace-context:v1 user-chars=(\d+)>>>\n$/.exec(header);
  if (!match) return undefined;

  const userLength = Number(match[1]);
  if (!Number.isSafeInteger(userLength) || userLength < 0 || userLength !== suffixStart) return content.slice(0, suffixStart);
  return content.slice(0, userLength);
}

function visibleLegacyWorkspacePrompt(content: string): string | undefined {
  const suffixStart = content.lastIndexOf("\n\n[Workspace reference: ");
  if (suffixStart === -1 || !content.endsWith("\n[End workspace reference]")) return undefined;
  const prompt = content.slice(0, suffixStart);
  const suffix = content.slice(suffixStart);
  const references = [...suffix.matchAll(/\n\n\[Workspace reference: ([^\]\r\n]+)\][\s\S]*?\n\[End workspace reference\]/g)];
  if (references.length === 0 || references.map((reference) => reference[0]).join("") !== suffix) return undefined;
  return prompt;
}

export function visibleWorkspacePrompt(content: string): string {
  return visibleMarkedWorkspacePrompt(content) ?? visibleLegacyWorkspacePrompt(content) ?? content;
}
